version: '3.8'
services:
  frontend:
    build: ../app/frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - villa-network

  backend:
    build: ../app/backend
    container_name: backend
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - villa-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - villa-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - villa-network

networks:
  villa-network:
    driver: bridge
